### ISSUE TITLE
JOBS_GRAPH is not defined

### ISSUE THREAD

**Issue by lagartoverde** [lblod/delta-producer-background-jobs-initiator#10]
```
ReferenceError: JOBS_GRAPH is not defined
    at updateStatusJob (/usr/src/output/app/lib/utils.js:174:43)
    at updateAndFilterTimedOutJobs (/usr/src/output/app/lib/utils.js:196:17)
    at run (/usr/src/output/app/jobs/dump-publication-graph.js:25:63)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async CronJob.<anonymous> (/usr/src/output/app/app.js:85:7)
     ```
Getting this error, and I don't see JOBS_GRAPH defined in that file so I think is an error of the service

**Comment by nbittich** [comment]
should be fixed in `1.0.1`
